var r=Object.defineProperty;var u=(a,t,s)=>t in a?r(a,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):a[t]=s;var n=(a,t,s)=>u(a,typeof t!="symbol"?t+"":t,s);import{r as i,j as m}from"./ConfirmationContext-DK_-GFGj.js";import p from"./Error-SULOs2Al.js";import"./Navbar-BhEc0PNi.js";import"./axiosInstance-Hn551h6z.js";class l extends i.Component{constructor(){super(...arguments);n(this,"state",{hasError:!1,errorStatus:void 0,errorMessage:void 0})}static getDerivedStateFromError(s){let e,o;return s!=null&&s.response?(e=s.response.status,o=s.response.statusText||s.message):s!=null&&s.status?(e=s.status,o=s.message):(e=void 0,o=(s==null?void 0:s.message)||"An unexpected error occurred."),{hasError:!0,errorStatus:e,errorMessage:o}}componentDidCatch(s,e){console.error("Caught by ErrorBoundary:",s,e)}render(){const{hasError:s,errorStatus:e,errorMessage:o}=this.state;return s?m.jsx(p,{status:e??500,message:o}):this.props.children}}export{l as ErrorBoundary};
